version: '3.8'
networks:
  stack:
    driver: bridge
services:
  npm:
    image: node:13.7
    container_name: npm
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - .:/var/www/html
    networks:
      - stack
  npx:
    image: node:13.7
    container_name: npx
    working_dir: /var/www/html
    entrypoint: ['npx']
    volumes:
      - .:/var/www/html
    networks:
      - stack